#!/usr/bin/env python3
"""Build an offline listening page for contextual WeSep outputs."""
import argparse,json
from pathlib import Path
import shutil

def build_html(items):
 data=json.dumps(items).replace('</','<\\/')
 return f'''<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>Contextual WeSep review</title><style>body{{font:16px system-ui;max-width:1050px;margin:24px auto;padding:0 16px;background:#f6f7f9;color:#17202a}}.card,.intro{{background:white;padding:16px;border-radius:10px;margin:16px 0}}video,audio{{width:100%;margin:6px 0}}label{{display:inline-block;margin:5px 14px 5px 0}}textarea{{width:100%;min-height:45px}}.done{{border-left:7px solid #1f9d55}}.sticky{{position:sticky;bottom:0;background:#eef2f7;padding:10px}}button{{font-size:16px;padding:10px;margin:5px}}.meta{{color:#52606d}}</style></head><body><h1>Contextual WeSep review</h1><div class="intro">Listen to the original video and all three extractions. For each contextual output, judge which speaker it contains. The transcript and similarity are shown only after the audio to keep the listening judgment primary.</div><div id="items"></div><div class="sticky"><span id="progress"></span><button onclick="download()">Download contextual-wesep-labels.json</button></div><script>
const items={data},key='contextual-wesep-review-v1',saved=JSON.parse(localStorage.getItem(key)||'{{}}'),choices=['target_only','mostly_target','mixed_speakers','mostly_other','other_only','no_intelligible_speech','unclear'];
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}}[c]));
function render(){{let root=document.getElementById('items');items.forEach((x,i)=>{{let v=saved[x.exchange_id]||{{}},c=document.createElement('div');c.className='card '+(v.context_3&&v.context_5?'done':'');let variants=x.variants.map(r=>`<h3>${{r.context_seconds}} seconds of context</h3><audio controls preload="none" src="${{esc(r.audio)}}"></audio><details><summary>Show machine measurements</summary><p>ASR: ${{esc(r.transcript)}}<br>Target similarity: ${{r.target_similarity.toFixed(3)}} · target-word F1: ${{r.target_word_f1.toFixed(2)}} · other-word F1: ${{r.other_word_f1.toFixed(2)}}</p></details><fieldset>${{choices.map(y=>`<label><input type="radio" name="${{x.exchange_id}}-${{r.context_seconds}}" data-f="context_${{r.context_seconds}}" value="${{y}}" ${{v['context_'+r.context_seconds]===y?'checked':''}}> ${{y.replaceAll('_',' ')}}</label>`).join('')}}</fieldset>`).join('');c.innerHTML=`<div class="meta">${{i+1}}/${{items.length}} · ${{x.start.toFixed(2)}}–${{x.end.toFixed(2)}} sec</div><p><b>Ground truth:</b> target “${{esc(x.target_words)}}”; other “${{esc(x.other_words)}}”</p><video controls preload="metadata" src="${{esc(x.video)}}"></video><h3>Current short-window extraction</h3><audio controls preload="none" src="${{esc(x.current_extraction)}}"></audio>${{variants}}<textarea placeholder="Optional comparison notes">${{esc(v.notes||'')}}</textarea>`;c.querySelectorAll('input,textarea').forEach(e=>e.oninput=e.onchange=()=>save(c,x.exchange_id));root.appendChild(c)}});progress()}}
function save(c,id){{let v={{notes:c.querySelector('textarea').value}};c.querySelectorAll('input:checked').forEach(e=>v[e.dataset.f]=e.value);saved[id]=v;localStorage.setItem(key,JSON.stringify(saved));c.classList.toggle('done',Boolean(v.context_3&&v.context_5));progress()}}function progress(){{progressEl=document.getElementById('progress');progressEl.textContent=`Reviewed ${{items.filter(x=>saved[x.exchange_id]?.context_3&&saved[x.exchange_id]?.context_5).length}} of ${{items.length}}`}}function download(){{let out={{schema_version:1,labels:items.map(x=>({{...x,...(saved[x.exchange_id]||{{}})}}))}},a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(out,null,2)],{{type:'application/json'}}));a.download='contextual-wesep-labels.json';a.click()}}render();</script></body></html>'''

def main():
 p=argparse.ArgumentParser();p.add_argument('--base-review',type=Path,required=True);p.add_argument('--labels',type=Path,required=True);p.add_argument('--experiment',type=Path,required=True);p.add_argument('--output-dir',type=Path,required=True);a=p.parse_args()
 base={x['exchange_id']:x for x in json.loads((a.base_review/'manifest.json').read_text())};labels={x['exchange_id']:x for x in json.loads(a.labels.read_text())['labels']};report=json.loads((a.experiment/'report.json').read_text())['results']
 if a.output_dir.exists():shutil.rmtree(a.output_dir)
 media=a.output_dir/'media';media.mkdir(parents=True);items=[]
 for eid,b in base.items():
  video=Path(b['video']).name;current=Path(b['current_extraction']).name;shutil.copy2(a.base_review/b['video'],media/video);shutil.copy2(a.base_review/b['current_extraction'],media/current);variants=[]
  for r in sorted((x for x in report if x['exchange_id']==eid),key=lambda x:x['context_seconds']):
   name=Path(r['audio']).name;shutil.copy2(a.experiment/r['audio'],media/name);variants.append({**r,'audio':f'media/{name}','transcript':r['transcription']['text']})
  lab=labels[eid];items.append({'exchange_id':eid,'start':b['start'],'end':b['end'],'video':f'media/{video}','current_extraction':f'media/{current}','target_words':lab.get('target_words',''),'other_words':lab.get('other_words',''),'variants':variants})
 (a.output_dir/'manifest.json').write_text(json.dumps(items,indent=2)+'\n');(a.output_dir/'index.html').write_text(build_html(items));print(f'Built {len(items)} contextual comparisons')
if __name__=='__main__':main()
