#!/usr/bin/env python3
"""Build a focused offline review page for shifted separation windows."""
import argparse,json,shutil
from pathlib import Path

def page(items):
 data=json.dumps(items).replace('</','<\\/')
 return f'''<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>Multi-offset separation review</title><style>body{{font:16px system-ui;max-width:1050px;margin:24px auto;padding:0 16px;background:#f6f7f9;color:#17202a}}.card,.intro{{background:white;padding:16px;border-radius:10px;margin:16px 0}}video,audio{{width:100%;margin:5px 0}}label{{display:inline-block;margin:5px 14px 5px 0}}textarea{{width:100%;min-height:45px}}.done{{border-left:7px solid #1f9d55}}.sticky{{position:sticky;bottom:0;background:#eef2f7;padding:10px}}button{{font-size:16px;padding:10px;margin:5px}}.variant{{border-top:1px solid #ccd;margin-top:15px}}.meta{{color:#52606d}}</style></head><body><h1>Multi-offset separation review</h1><div class="intro">For the early and late windows, choose which stream contains the target. Stream numbers may swap between windows. The center-window decision from your earlier review is shown for comparison.</div><div id="root"></div><div class="sticky"><span id="progress"></span><button onclick="download()">Download multi-offset-labels.json</button></div><script>
const items={data},key='multi-offset-review-v1',saved=JSON.parse(localStorage.getItem(key)||'{{}}'),choices=['stream_1','stream_2','neither','unclear'];const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}}[c]));
function render(){{items.forEach((x,i)=>{{let v=saved[x.exchange_id]||{{}},c=document.createElement('div');c.className='card '+(v.offset_minus_1&&v.offset_plus_1?'done':'');let variants=x.offsets.map(o=>`<div class="variant"><h3>${{o.offset>0?'+':''}}${{o.offset}} second offset</h3>${{o.streams.map(s=>`<p>Stream ${{s.stream}}</p><audio controls preload="none" src="${{esc(s.audio)}}"></audio><details><summary>Show machine transcript</summary>${{esc(s.transcript)}} · similarity ${{s.target_similarity.toFixed(3)}}</details>`).join('')}}<fieldset><legend>Which stream contains the target?</legend>${{choices.map(y=>`<label><input type="radio" name="${{x.exchange_id}}-${{o.offset}}" data-f="${{o.offset<0?'offset_minus_1':'offset_plus_1'}}" value="${{y}}" ${{v[o.offset<0?'offset_minus_1':'offset_plus_1']===y?'checked':''}}> ${{y.replaceAll('_',' ')}}</label>`).join('')}}</fieldset></div>`).join('');c.innerHTML=`<div class="meta">${{i+1}}/${{items.length}} · ${{x.start.toFixed(2)}}–${{x.end.toFixed(2)}} sec</div><p><b>Ground truth:</b> target “${{esc(x.target_words)}}”; other “${{esc(x.other_words)}}”</p><p><b>Earlier center-window choice:</b> ${{esc(x.center_target_stream)}}</p><video controls preload="metadata" src="${{esc(x.video)}}"></video>${{variants}}<textarea placeholder="Optional notes">${{esc(v.notes||'')}}</textarea>`;c.querySelectorAll('input,textarea').forEach(e=>e.oninput=e.onchange=()=>save(c,x.exchange_id));root.appendChild(c)}});progress()}}
function save(c,id){{let v={{notes:c.querySelector('textarea').value}};c.querySelectorAll('input:checked').forEach(e=>v[e.dataset.f]=e.value);saved[id]=v;localStorage.setItem(key,JSON.stringify(saved));c.classList.toggle('done',Boolean(v.offset_minus_1&&v.offset_plus_1));progress()}}function progress(){{document.getElementById('progress').textContent=`Reviewed ${{items.filter(x=>saved[x.exchange_id]?.offset_minus_1&&saved[x.exchange_id]?.offset_plus_1).length}} of ${{items.length}}`}}function download(){{let out={{schema_version:1,labels:items.map(x=>({{...x,...(saved[x.exchange_id]||{{}})}}))}},a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(out,null,2)],{{type:'application/json'}}));a.download='multi-offset-labels.json';a.click()}}render();</script></body></html>'''

def main():
 p=argparse.ArgumentParser();p.add_argument('--base-review',type=Path,required=True);p.add_argument('--center-labels',type=Path,required=True);p.add_argument('--experiment',type=Path,required=True);p.add_argument('--output-dir',type=Path,required=True);a=p.parse_args();base={x['exchange_id']:x for x in json.loads((a.base_review/'manifest.json').read_text())};center={x['exchange_id']:x for x in json.loads(a.center_labels.read_text())['labels']};rows=json.loads((a.experiment/'report.json').read_text())['results']
 if a.output_dir.exists():shutil.rmtree(a.output_dir)
 media=a.output_dir/'media';media.mkdir(parents=True);items=[]
 for eid in sorted({r['exchange_id'] for r in rows}):
  b=base[eid];video=Path(b['video']).name;shutil.copy2(a.base_review/b['video'],media/video);offsets=[]
  for r in sorted((x for x in rows if x['exchange_id']==eid),key=lambda x:x['window_offset_seconds']):
   streams=[]
   for s in r['streams']:
    name=Path(s['audio']).name;shutil.copy2(a.experiment/s['audio'],media/name);streams.append({**s,'audio':f'media/{name}','transcript':s['transcription']['text']})
   offsets.append({'offset':r['window_offset_seconds'],'streams':streams})
  c=center[eid];items.append({'exchange_id':eid,'start':b['start'],'end':b['end'],'target_words':c['target_words'],'other_words':c['other_words'],'center_target_stream':c['target_stream'],'video':f'media/{video}','offsets':offsets})
 (a.output_dir/'manifest.json').write_text(json.dumps(items,indent=2)+'\n');(a.output_dir/'index.html').write_text(page(items));print(f'Built {len(items)} multi-offset comparisons')
if __name__=='__main__':main()
