#!/usr/bin/env python3
"""Build an offline listening page for blind two-output separation."""
import argparse,json,shutil
from pathlib import Path

def html(items, storage_key='two-output-review-v1', download_name='two-output-labels.json'):
 data=json.dumps(items).replace('</','<\\/')
 key_json=json.dumps(storage_key);download_json=json.dumps(download_name)
 return f'''<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>Two-output separation review</title><style>body{{font:16px system-ui;max-width:1050px;margin:24px auto;padding:0 16px;background:#f6f7f9;color:#17202a}}.card,.intro{{background:white;padding:16px;border-radius:10px;margin:16px 0}}video,audio{{width:100%;margin:7px 0}}label{{display:inline-block;margin:5px 14px 5px 0}}textarea{{width:100%;min-height:44px}}.done{{border-left:7px solid #1f9d55}}.sticky{{position:sticky;bottom:0;background:#eef2f7;padding:10px}}button{{font-size:16px;padding:10px;margin:5px}}.meta{{color:#52606d}}</style></head><body><h1>Blind two-output separation review</h1><div class="intro">Listen to the original, then classify each separated stream. Choose the target stream from listening; machine similarity is hidden under details until afterward.</div><div id="root"></div><div class="sticky"><span id="progress"></span><button onclick="download()">Download two-output-labels.json</button></div><script>
const items={data},key={key_json},saved=JSON.parse(localStorage.getItem(key)||'{{}}'),choices=['target_only','mostly_target','mixed_speakers','mostly_other','other_only','no_intelligible_speech','unclear'];const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}}[c]));
function render(){{items.forEach((x,i)=>{{let v=saved[x.exchange_id]||{{}},c=document.createElement('div');c.className='card '+(v.stream_1&&v.stream_2&&v.target_stream?'done':'');let streams=x.streams.map(s=>`<h3>Stream ${{s.stream}}</h3><audio controls preload="none" src="${{esc(s.audio)}}"></audio><fieldset>${{choices.map(y=>`<label><input type="radio" name="${{x.exchange_id}}-s${{s.stream}}" data-f="stream_${{s.stream}}" value="${{y}}" ${{v['stream_'+s.stream]===y?'checked':''}}> ${{y.replaceAll('_',' ')}}</label>`).join('')}}</fieldset><details><summary>Show machine measurements</summary>ASR: ${{esc(s.transcript)}}<br>Target similarity: ${{s.target_similarity.toFixed(3)}} · target-word F1: ${{s.target_word_f1.toFixed(2)}} · other-word F1: ${{s.other_word_f1.toFixed(2)}}</details>`).join('');c.innerHTML=`<div class="meta">${{i+1}}/${{items.length}} · ${{x.start.toFixed(2)}}–${{x.end.toFixed(2)}} sec</div><p><b>Ground truth:</b> target “${{esc(x.target_words)}}”; other “${{esc(x.other_words)}}”</p><video controls preload="metadata" src="${{esc(x.video)}}"></video>${{streams}}<fieldset><legend>Which output best contains the target?</legend>${{['stream_1','stream_2','neither','target_not_present','unclear'].map(y=>`<label><input type="radio" name="${{x.exchange_id}}-target" data-f="target_stream" value="${{y}}" ${{v.target_stream===y?'checked':''}}> ${{y.replaceAll('_',' ')}}</label>`).join('')}}</fieldset><textarea placeholder="Optional notes">${{esc(v.notes||'')}}</textarea>`;c.querySelectorAll('input,textarea').forEach(e=>e.oninput=e.onchange=()=>save(c,x.exchange_id));root.appendChild(c)}});progress()}}
function save(c,id){{let v={{notes:c.querySelector('textarea').value}};c.querySelectorAll('input:checked').forEach(e=>v[e.dataset.f]=e.value);saved[id]=v;localStorage.setItem(key,JSON.stringify(saved));c.classList.toggle('done',Boolean(v.stream_1&&v.stream_2&&v.target_stream));progress()}}function progress(){{document.getElementById('progress').textContent=`Reviewed ${{items.filter(x=>saved[x.exchange_id]?.stream_1&&saved[x.exchange_id]?.stream_2&&saved[x.exchange_id]?.target_stream).length}} of ${{items.length}}`}}function download(){{let out={{schema_version:1,labels:items.map(x=>({{...x,...(saved[x.exchange_id]||{{}})}}))}},a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(out,null,2)],{{type:'application/json'}}));a.download={download_json};a.click()}}render();</script></body></html>'''

def main():
 p=argparse.ArgumentParser();p.add_argument('--base-review',type=Path,required=True);p.add_argument('--experiment',type=Path,required=True);p.add_argument('--output-dir',type=Path,required=True);p.add_argument('--storage-key',default='two-output-review-v1');p.add_argument('--download-name',default='two-output-labels.json');a=p.parse_args();base={x['exchange_id']:x for x in json.loads((a.base_review/'manifest.json').read_text())};report=json.loads((a.experiment/'report.json').read_text())['results']
 if a.output_dir.exists():shutil.rmtree(a.output_dir)
 media=a.output_dir/'media';media.mkdir(parents=True);items=[]
 for row in report:
  b=base[row['exchange_id']];video=Path(b['video']).name;shutil.copy2(a.base_review/b['video'],media/video);streams=[]
  for s in row['streams']:
   name=Path(s['audio']).name;shutil.copy2(a.experiment/s['audio'],media/name);streams.append({**s,'audio':f'media/{name}','transcript':s['transcription']['text']})
  items.append({'exchange_id':row['exchange_id'],'start':row['start'],'end':row['end'],'target_words':row['target_words'],'other_words':row['other_words'],'video':f'media/{video}','streams':streams,'similarity_selected_stream':row['similarity_selected_stream'],'similarity_margin':row['similarity_margin']})
 (a.output_dir/'manifest.json').write_text(json.dumps(items,indent=2)+'\n');(a.output_dir/'index.html').write_text(html(items,a.storage_key,a.download_name));print(f'Built {len(items)} two-output comparisons')
if __name__=='__main__':main()
