#!/usr/bin/env python3
"""Build a focused review for timestamp-aligned full-context separated ASR."""
import argparse,json,shutil
from pathlib import Path

def html(items):
 data=json.dumps(items).replace('</','<\\/')
 return f'''<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>Context-aligned separated ASR review</title><style>body{{font:16px system-ui;max-width:1050px;margin:24px auto;padding:0 16px;background:#f6f7f9;color:#17202a}}.card,.intro{{background:white;padding:16px;border-radius:10px;margin:16px 0}}video,audio{{width:100%;margin:5px 0}}label{{display:inline-block;margin:5px 14px 5px 0}}textarea{{width:100%;min-height:42px}}.done{{border-left:7px solid #1f9d55}}.variant{{border-top:1px solid #ccd;margin-top:16px}}.sticky{{position:sticky;bottom:0;background:#eef2f7;padding:10px}}button{{font-size:16px;padding:10px;margin:5px}}.meta{{color:#52606d}}</style></head><body><h1>Context-aligned separated ASR review</h1><div class="intro">Listen to the full separated stream for context. Then judge whether the words aligned to the original short interval are correct. The interval remains fixed even though the audio player includes surrounding speech.</div><div id="root"></div><div class="sticky"><span id="progress"></span><button onclick="download()">Download context-aligned-asr-labels.json</button></div><script>
const items={data},key='context-aligned-asr-review-v1',saved=JSON.parse(localStorage.getItem(key)||'{{}}'),choices=['correct','mostly_correct','incorrect','unclear'];const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}}[c]));
function render(){{items.forEach((x,i)=>{{let v=saved[x.exchange_id]||{{}},c=document.createElement('div'),required=x.variants.map(o=>'offset_'+String(o.offset).replace('-','minus_').replace('+','')).every(k=>v[k]);c.className='card '+(required?'done':'');let variants=x.variants.map(o=>{{let k='offset_'+String(o.offset).replace('-','minus_').replace('+','');return `<div class="variant"><h3>${{o.offset>0?'+':''}}${{o.offset}} second window · candidate stream ${{o.stream}}</h3><audio controls preload="none" src="${{esc(o.audio)}}"></audio><p>Words aligned to the interval: <b>${{esc(o.aligned_text)||'(none)'}}</b></p><fieldset>${{choices.map(y=>`<label><input type="radio" name="${{x.exchange_id}}-${{o.offset}}" data-f="${{k}}" value="${{y}}" ${{v[k]===y?'checked':''}}> ${{y.replaceAll('_',' ')}}</label>`).join('')}}</fieldset></div>`}}).join('');c.innerHTML=`<div class="meta">${{i+1}}/${{items.length}} · ${{x.start.toFixed(2)}}–${{x.end.toFixed(2)}} sec</div><p><b>Known target words:</b> ${{esc(x.target_words)}}</p><video controls preload="metadata" src="${{esc(x.video)}}"></video>${{variants}}<textarea placeholder="Corrected words or notes">${{esc(v.notes||'')}}</textarea>`;c.querySelectorAll('input,textarea').forEach(e=>e.oninput=e.onchange=()=>save(c,x.exchange_id));root.appendChild(c)}});progress()}}
function save(c,id){{let v={{notes:c.querySelector('textarea').value}};c.querySelectorAll('input:checked').forEach(e=>v[e.dataset.f]=e.value);saved[id]=v;localStorage.setItem(key,JSON.stringify(saved));c.classList.toggle('done',c.querySelectorAll('input:checked').length===3);progress()}}function progress(){{let done=items.filter(x=>x.variants.every(o=>saved[x.exchange_id]?.['offset_'+String(o.offset).replace('-','minus_').replace('+','')])).length;document.getElementById('progress').textContent=`Reviewed ${{done}} of ${{items.length}}`}}function download(){{let out={{schema_version:1,labels:items.map(x=>({{...x,...(saved[x.exchange_id]||{{}})}}))}},a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(out,null,2)],{{type:'application/json'}}));a.download='context-aligned-asr-labels.json';a.click()}}render();</script></body></html>'''

def main():
 p=argparse.ArgumentParser();p.add_argument('--base-review',type=Path,required=True);p.add_argument('--center-labels',type=Path,required=True);p.add_argument('--offset-labels',type=Path,required=True);p.add_argument('--experiment',type=Path,required=True);p.add_argument('--output-dir',type=Path,required=True);a=p.parse_args();base={x['exchange_id']:x for x in json.loads((a.base_review/'manifest.json').read_text())};center={x['exchange_id']:x for x in json.loads(a.center_labels.read_text())['labels']};shifted={x['exchange_id']:x for x in json.loads(a.offset_labels.read_text())['labels']};rows=json.loads((a.experiment/'report.json').read_text())['results']
 if a.output_dir.exists():shutil.rmtree(a.output_dir)
 media=a.output_dir/'media';media.mkdir(parents=True);items=[]
 for eid in sorted({r['exchange_id'] for r in rows}):
  b=base[eid];video=Path(b['video']).name;shutil.copy2(a.base_review/b['video'],media/video);variants=[]
  for r in sorted((x for x in rows if x['exchange_id']==eid),key=lambda x:x['window_offset_seconds']):
   offset=r['window_offset_seconds'];choice=center[eid]['target_stream'] if offset==0 else shifted[eid]['offset_minus_1' if offset<0 else 'offset_plus_1']
   if choice.startswith('stream_'):number=int(choice.split('_')[1])
   else:number=max(r['streams'],key=lambda s:s['target_word_f1'])['stream']
   s=next(x for x in r['streams'] if x['stream']==number);name=Path(s['full_audio']).name;shutil.copy2(a.experiment/s['full_audio'],media/name);variants.append({'offset':offset,'stream':number,'selection_basis':'prior_human_target' if choice.startswith('stream_') else 'highest_target_word_match_for_review','audio':f'media/{name}','aligned_text':s['aligned_transcription'],'full_text':s['full_context_transcription']})
  items.append({'exchange_id':eid,'start':b['start'],'end':b['end'],'target_words':center[eid]['target_words'],'video':f'media/{video}','variants':variants})
 (a.output_dir/'manifest.json').write_text(json.dumps(items,indent=2)+'\n');(a.output_dir/'index.html').write_text(html(items));print(f'Built {len(items)} aligned-ASR comparisons')
if __name__=='__main__':main()
